"""
Trip Swarm — models.py
SQLAlchemy ORM models for PostgreSQL
"""

from datetime import datetime
from sqlalchemy import (
    Column, Integer, BigInteger, String, Text,
    DateTime, ForeignKey
)
from sqlalchemy.orm import relationship, declarative_base

Base = declarative_base()


class User(Base):
    """Google OAuth users."""
    __tablename__ = "users"

    id        = Column(Integer, primary_key=True, index=True)
    google_id = Column(String(128), unique=True, index=True, nullable=False)
    email     = Column(String(255), unique=True, index=True, nullable=False)
    name      = Column(String(255), nullable=False)
    picture   = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    threads   = relationship("ChatThread",  back_populates="user", cascade="all, delete-orphan")
    reports   = relationship("TripReport",  back_populates="user", cascade="all, delete-orphan")
    documents = relationship("UserDocument",back_populates="user", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<User id={self.id} email={self.email}>"


class ChatThread(Base):
    """
    A conversation thread — either a trip planning session (travel)
    or a RAG Q&A session (rag). Each thread belongs to one user.
    """
    __tablename__ = "chat_threads"

    id          = Column(Integer, primary_key=True, index=True)
    user_id     = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    thread_type = Column(String(20), nullable=False, default="travel")  # "travel" | "rag"
    title       = Column(String(512), nullable=False, default="New Chat")
    created_at  = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at  = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    user     = relationship("User",        back_populates="threads")
    messages = relationship("ChatMessage", back_populates="thread", cascade="all, delete-orphan")
    reports  = relationship("TripReport",  back_populates="thread")

    def __repr__(self):
        return f"<ChatThread id={self.id} type={self.thread_type} user={self.user_id}>"


class ChatMessage(Base):
    """
    A single message within a thread.
    Stores full conversational memory per thread per user.
    role: "user" | "assistant"
    """
    __tablename__ = "chat_messages"

    id         = Column(Integer, primary_key=True, index=True)
    thread_id  = Column(Integer, ForeignKey("chat_threads.id", ondelete="CASCADE"), nullable=False, index=True)
    user_id    = Column(Integer, ForeignKey("users.id",        ondelete="CASCADE"), nullable=False, index=True)
    role       = Column(String(20),  nullable=False)   # "user" | "assistant"
    content    = Column(Text,        nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    thread = relationship("ChatThread", back_populates="messages")

    def __repr__(self):
        return f"<ChatMessage id={self.id} role={self.role} thread={self.thread_id}>"


class TripReport(Base):
    """
    Full trip plan reports generated by the travel AI agents.
    Stored in PostgreSQL for the user's "Saved Trips" tab.
    """
    __tablename__ = "trip_reports"

    id         = Column(Integer, primary_key=True, index=True)
    user_id    = Column(Integer, ForeignKey("users.id",         ondelete="CASCADE"),   nullable=False, index=True)
    thread_id  = Column(Integer, ForeignKey("chat_threads.id", ondelete="SET NULL"),  nullable=True)
    title      = Column(String(512), nullable=False)
    content    = Column(Text,        nullable=False)   # Full report markdown text
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    user   = relationship("User",       back_populates="reports")
    thread = relationship("ChatThread", back_populates="reports")

    def __repr__(self):
        return f"<TripReport id={self.id} user={self.user_id} title={self.title[:40]}>"


class UserDocument(Base):
    """
    Metadata for user-uploaded documents.
    The actual text/embeddings live in ChromaDB, tagged with user_id.
    This table tracks what the user has uploaded for the UI.
    """
    __tablename__ = "user_documents"

    id             = Column(Integer,    primary_key=True, index=True)
    user_id        = Column(Integer,    ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    filename       = Column(String(255),nullable=False)
    chroma_doc_id  = Column(String(255),nullable=True)   # UUID used as doc_id in Chroma metadata
    file_size      = Column(BigInteger, default=0)
    content_type   = Column(String(100),nullable=True)
    created_at     = Column(DateTime,  default=datetime.utcnow, nullable=False)

    user = relationship("User", back_populates="documents")

    def __repr__(self):
        return f"<UserDocument id={self.id} filename={self.filename} user={self.user_id}>"
